### ISSUE TITLE
Eatlocal livelocks when submitting a bite if git has not been configured.

### ISSUE THREAD

**Issue by rhelmstedter** [PyBites-Open-Source/eatlocal#20]
Issue:
On a new machine (Ubuntu linux), I tried submitting bite 136. eatlocal gets stuck trying to submit. I have to abort with \<C-c\>. While attempting to manually add and commit the bite with git, I got a Author identity unknown.

Expected behavior:
catch error using git python, pass the error onto the user and exit program.

**Comment by WillCodesThings** [comment]
Maybe implement a timer feature, if too much time has passed a certain threshold then just tell user that it is currently unable to submit answer and give them a debug statement?

**Comment by rhelmstedter** [comment]
No longer relying on git to submit bites.
