### ISSUE TITLE
Init mode

### ISSUE THREAD

**Issue by pmayd** [PyBites-Open-Source/eatlocal#27]
I just thought about an init mode. This could be used to ask the user for username and password so they don't have to create env vars before using eatlocal. In addition we could register the current working director as bite repo, or ask the user about this, too. So all three constants would be stored once you run eatlocal init. And if you want to change any of the three you can run the command again. Not sure if we can permanently set env vars with os.env, I think this was only temporarily, but I propose to create a .eatlocal/.credentials file in the home directory that is read at the beginning of each run of eatlocal to have the latest variables. Maybe there is a better way so I have to research how to set env vars with python but this would make the tool easier for people who are not familiar with this kind of things

**Comment by rhelmstedter** [comment]
I love this idea. I'll create an init branch and test out your commit.

**Comment by rhelmstedter** [comment]
One issue that I noticed is that it did not expand the `~`. I tried setting it up on my work computer running linux. I will see if typer has something built in to handle this.

![image](https://user-images.githubusercontent.com/70656244/165978910-7ed9b4f8-857b-41bf-b25d-ff727146cc79.png)

**Comment by pmayd** [comment]
OK I am a little lost here, what is happening and where does ne "~" come from? It seems `Path().home()` is correctly resolved to /home/deanza/.eatlocal, as the green text implies. But your current working directory is ~/eatlocal? So the download Path is not correct but this has nothing to do with the init command right? The init command creates a `.env` file in the `.eatlocal` hidden folder and that has worked because the download command successfully downloads the bite so the user credentails where correctly found and read in.

Ah maybe the repo link is wrong? Your screen does not show the very important line BEFORE the confirmation ask, what is the content of the repo variable? Can you show me the value of PYBITES_REPO? I implemented it so that if you don't give a specific path it takes the current working directory and maybe because the current working directory is ~/eatlocal he stored it with the "~". So the fix is easy, I have to use `resolve()` as this is the only reason you need this method when working with Path, to resolve the user directory "~".

**Comment by rhelmstedter** [comment]
> Your screen does not show the very important line BEFORE the confirmation ask, what is the content of the repo variable? Can you show me the value of PYBITES_REPO? 

Sorry, I had to crop that piece because it displayed my actual password. I had typed in `~/pybites`.

`~` is a unix short hand for the user home. When I tried it with `.resolve()` it was creating a new directory in my current working directory `/home/user/eatlocal/~/pybites`. I got this to work using `os.path.expanduser()`.

![image](https://user-images.githubusercontent.com/70656244/165988012-67f455dd-bf93-40e8-99d2-849027ca50dc.png)

**Comment by pmayd** [comment]
Yep that is what I described, if you enter such a path there might be a problem but this has to be possible with Path to, os is considered deprecated and should not be used unless necessary and the documentation of home() references os expanduser so I will test it

**Comment by rhelmstedter** [comment]
Ooo I just saw there is a `Path.expanduser()`

**Comment by pmayd** [comment]
Yes but this should be identical to home()

**Comment by pmayd** [comment]
OK you are right but I don't get it why resolve() is not doint this...
If you have a path that starts with "~" you need:
```
>>> p = PosixPath('~/films/Monty Python')
>>> p.expanduser()
PosixPath('/home/eric/films/Monty Python')
```

So I guess we have to check if the path starts with that

**Comment by pmayd** [comment]
It seems that expanduser is not doing anything to a Path without "~" this is great! And even under windows it works! The normal cmd does not support "~" like UNIX systems but Path allows it!

```
Path("~/.eatlocal").expanduser()
Out[13]: WindowsPath('C:/Users/micha/.eatlocal')
```

This means we just have to use expanduser() when we access config["PYBITES_REPO"] or even better before we store it in the init command

**Comment by pmayd** [comment]
Should be fixed by the new PR

**Comment by rhelmstedter** [comment]
Awesome. Just merged it and am super excited. I think it will be was easier for new users. Thanks for doing this.

Some thoughts:
Are there security concerns with displaying the password? Would it be better to use the confirm option in typer?

**Comment by pmayd** [comment]
But sure, feel free to look for alternative approaches ;)

**Comment by rhelmstedter** [comment]
> This is important because the download command does not tell of the credentials are correct, the download just won't work but you are not told the reason why.

This makes me think I should look into checking that the credentials are accepted on codechalleng.es.

>We could omit the display if the user input as you suggest and ask the user to make sure that the content of the env file is correct but I don't think that our package will be used in any real world scenario where anyone could steel your pybites credentials...

I am fine with displaying everything as long as people using the tool don't have concerns. It just feels odd to hide the password during input, only to display it later. I think we should either keep it hidden, while asking for confirmation to help with typos, and not display it. Or just display it the entire time like the user name.

**Comment by pmayd** [comment]
Yes, my thoughts exactly.

Maybe we do a two-fold confirmation so you have to enter your password two
times, hidden, and only if they match and you confirm the other two
variables, we move on

Russell ***@***.***> schrieb am Fr., 29. Apr. 2022, 22:41:

**Comment by rhelmstedter** [comment]
Yes, I agree. Do you want to handle that or should I?

**Comment by pmayd** [comment]
Feel free :)

**Comment by rhelmstedter** [comment]
This might be a dumb question, but where did you find the documentation for `Prompt.ask`? I couldn't find it by searching on https://typer.tiangolo.com/.

**Comment by pmayd** [comment]
Yes the documentation is lacking a lot in this regard I went strait to the source code where all attributes a described properly

**Comment by rhelmstedter** [comment]
Found a nice little bug too. Back on my home machine where I have no `.eatlocal/.env` file, I get the warning to run `eatlocal init` even though I am. I believe this is happening because `__main__.py` is trying to import config from `constants.py`.

![image](https://user-images.githubusercontent.com/70656244/166115133-99504a07-e04d-4bc1-9608-aa6f3b2b22f3.png)

**Comment by pmayd** [comment]
This is not a Bug but the expected behavior of how I implemented it. eatlocal is checking before anything else if it can load the .env file and if that is not possible ,displays the warning. I am not sure how to check if the current command is `init` and not display this warning. We would have to delay the check of the `.env` file to later, but we need it in constants so that the necessary variables can be loaded...

**Comment by pmayd** [comment]
Exactly, constants.py is loaded at the beginning even before eatlocal is doing anything, so I used this to inform the user that eatlocal is not yet fully functional. The good thing is that this warning will disappear once you have run the init command successfully :P

**Comment by rhelmstedter** [comment]
hmmm can we import `load_config()` and just call it in all of the commands except init? And if the env_path doesn't exist display the warning and exit. Currently it will display the warning but continue trying to download (or whatever). Or am I overthinking it? 😂 

![image](https://user-images.githubusercontent.com/70656244/166115923-17604cbe-6857-48c9-b5c9-6d4d4b29c673.png)

**Comment by pmayd** [comment]
Absolutely, I guess I wanted it to be done before any command so that it is happening on a global level and I am sure there is some way to do this, decorator for example would be a nice exercise but yes this would be a better approach and we avoid that the commands go forth.

Originally I had implemented it directly in the first check so that the program would exit...realizing only later that now it was impossible to ever call even the init command haha.

I can do it or leave it to you

**Comment by rhelmstedter** [comment]
>realizing only later that now it was impossible to ever call even the init command haha.

Same! I almost made it so that was the case, haha. I'll attempt it :). It's good for my learning.

**Comment by rhelmstedter** [comment]
here it is: 35cc0270caee94b24055547a2468a3f5479ca1ef

**Comment by pmayd** [comment]
commented, but otherwise fine!

**Comment by Zaubeerer** [comment]
`eatlocal init` seems to not have worked properly for me, as there is no file created in `/../.eatlocal` 🤔

**Comment by ExxetaMAydinbas** [comment]
Did you get a success message? 
`print(f"[green]Successfully stored configuration variables under {EATLOCAL_HOME}.")`
What was the content of the variable EATLOCAL_HOME for you?

**Comment by Zaubeerer** [comment]
The config was successfully created and contains the required information :)

On my Mac M1, `eatlocal` now works perfectly.

However, on my Windows machine, there are still issues.

Not sure, whether this is related to the initialization or something else, so I created this issue https://github.com/PyBites-Open-Source/eatlocal/issues/31.

**Comment by rhelmstedter** [comment]
@Zaubeerer Just responded to your other issue. I'll leave this open until we completely rule out the init mode as the issue on your Windows machine.

**Comment by Zaubeerer** [comment]
Just solved the problem on the windows machine.

See #31 for more information.
