### ISSUE TITLE
Python3.10 update

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/eatlocal#34]
I see this in the README:

> eatlocal is now compatible with Python 3.8. This matches the expected python version for the platform.

The platform uses 3.10 now so shall we upgrade `eatlocal` to use this version too? Should be backwards compatible, but would be nice to match the versions.

**Comment by rhelmstedter** [comment]
Yeah, I like that idea. I think we can upgrade versions without a problem. The only issue we had before was type hinting.

**Comment by rhelmstedter** [comment]
V2 uses 3.12. Closing this issue.
