### ISSUE TITLE
Support google / github login

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/eatlocal#38]
eatlocal v1 never supported goolge/github login. We gave users who used google/github the option to set a password in their profile/dashboard page (I don't remember which one).

_Originally posted by @rhelmstedter in https://github.com/PyBites-Open-Source/eatlocal/pull/36#discussion_r1829433600_

**Comment by rhelmstedter** [comment]
That would be the easier for me lol. But seriously, my concern would be 2FA for google and Github. If the user has to open their phone, or enter a verification code, I'm not sure how to handle that via playwright.

**Comment by bbelderbos** [comment]
Yeah good point, let me put password setting back to v2 then ...

**Comment by rhelmstedter** [comment]
Cool, Then it would be a matter of changing the documentation. "If you logged in with google/github" set a password for your account."

**Comment by bbelderbos** [comment]
Yep I already have this locally coded so let's go this way, please update the docs as suggested on your download-bite fix branch ...

**Comment by bbelderbos** [comment]
Done, you can now set a pw:

![image](https://github.com/user-attachments/assets/b0ec5088-e690-4c1d-b64d-db83cb0c6ac6)
