### ISSUE TITLE
Make eatlocal work for newbies + intros as well (not only regular Bites)

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/eatlocal#43]
Got it. I only check if the user can't log in. I forgot about users who can log it, but don't have premium access. I'll work on that in a new branch.

v1 didn't work for newbies. I think it shouldn't be too difficult to add. Should be just navigating to the newbie and intro tables and adding them to the dictionary. 

@olgamirth do either of these issues interest you?

_Originally posted by @rhelmstedter in https://github.com/PyBites-Open-Source/eatlocal/issues/40#issuecomment-2465022598_

**Comment by bbelderbos** [comment]
https://pybitesplatform.com/api/bites/ -> FYI level attribute is there

**Comment by rhelmstedter** [comment]
I started using the api @bbelderbos provided in [2b954ad](https://github.com/PyBites-Open-Source/eatlocal/pull/44/commits/2b954ad10357e607699122860968b79c34875dba).
