### ISSUE TITLE
Speed up eatlocal download bite listing

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/eatlocal#48]
The new bite api endpoint is pretty static, we don't even add new bites every week and titles don't change often.

So let's add caching and with requests this is very easy:
https://pybitesplatform.com/tips/caching-api-calls

This will make the sub command respond instantly leveraging a local sqlite db, something the user does not even notices.

pybites-search is so fast using this same technique: 
https://github.com/PyBites-Open-Source/search/blob/main/src/pybites_search/base.py#L26

@rhelmstedter what do you think?

**Comment by rhelmstedter** [comment]
I didn't see your last comment until afterward. But what I ended up doing was setting the cache to expire after 30 days, but added a `--clear-cache` flag for the user if needed. I think that is a good in-between. [a3b391d](https://github.com/PyBites-Open-Source/eatlocal/pull/49/commits/a3b391d466108a42804453afd66217959681a0a4)

**Comment by bbelderbos** [comment]
That's perfect, thanks!

**Comment by bbelderbos** [comment]
implemented https://github.com/PyBites-Open-Source/eatlocal/pull/49
