### ISSUE TITLE
test_submit_command e2e fails locally for me (probably due to lacking bite access)  

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/eatlocal#54]
@rhelmstedter `test_submit_command` failed for me locally:

```
mock_iterfzf = <MagicMock name='iterfzf' id='4374275008'>, mock_load_config = <MagicMock name='load_config' id='4375727472'>
testing_config = {'PYBITES_PASSWORD': ... 'PYBITES_REPO': PosixPath('/Users/bbelderbos/code/eatlocal/tests/testing_repo'), 'PYBITES_USERNAME': ...}
...
        mock_iterfzf.return_value = "Rotate string characters"
...
>       assert "Code did not pass the tests." in result.output
E       assert 'Code did not pass the tests.' in ''
E        +  where '' = <Result Error("Page.evaluate: TypeError: Cannot read properties of null (reading 'CodeMirror')\n    at eval (eval at e...anonymous>)\n    at UtilityScript.evaluate (<anonymous>:234:30)\n    at UtilityScript.<anonymous> (<anonymous>:1:44)")>.output
```

Could it be because my user does not have access to this premium Bite? Would it be better to use a free (intro) Bite so not all developers on this project have to have premium access?

**Comment by rhelmstedter** [comment]
I chose that one because it was premium and wanted to test that authenticating with playwright (selenium back in the day) worked. But, if you want, we can use a free one for other contributors can run the tests without have access.

**Comment by bbelderbos** [comment]
It would be a bit more accessible I think, thanks. For auth flow it's the same right?

**Comment by rhelmstedter** [comment]
@bbelderbos I believe this was resolved in the last PR. If not, feel free to reopen the issue.
