### ISSUE TITLE
eatlocal submit fails on missing .local_bites.json file in repo directory.

### ISSUE THREAD

**Issue by NielsU** [PyBites-Open-Source/eatlocal#55]
Am working on windows. After running eatlocal init the .local_bites.json is put in my user home directory. 

The local bites json is updated at that location, however my pybites repo is in another path. 

Eatlocal submit seems to expect the .local_bites.json in the pybites repo, which (in my case) is not correct. 

![image](https://github.com/user-attachments/assets/a892ab79-3b69-4771-9894-220093cf0340)

**Comment by rhelmstedter** [comment]
Thanks for letting us know. I just merged a pull request and it should be fixed now. It will look in the home/.eatlocal on your machine. You will just need to update eatlocal to version 1.1.3.

We are taking this week off for Thanksgiving (for me starting tomorrow). If you run into anything else let me know and we'll get back to you next week.

**Comment by NielsU** [comment]
Thanks for the swift fix! Somehow uv did not replace the package code at update, had to remove it. After new install it works. :)

**Comment by rhelmstedter** [comment]
Glad we fixed the issue.

When I used to use pipx, if I had recently installed a package, fixed a bug, and then try to upgrade to the newest version, it would not get the most recent version unless I added the `--force` flag.

I'm guessing `uv` works the same way? Glancing at [the docs](https://docs.astral.sh/uv/concepts/tools/), it seems like `uv tool upgrade eatlocal@latest` might work?
